### ISSUE TITLE
Folders not working and animated tiles dont animate

### ISSUE THREAD

**Issue by 5H4D0WILA** [mapeditor/tiled-to-godot-export#13]
Hey, first of all, thank you so much for this extension. 
Me and my team are recreating Pokemon Uranium in godot and your extension makes it so much easier.
That being said, i have encountered a few small things that arent working correctly:
When using folders in the tiled file, the tscn file will be an empty scene with only a node2d as root
and when i have animated tiles, they get converted to normal tiles
would it be possible to fix these two things?
best regards

**Comment by MikeMnD** [comment]
I wouldn't take this request at the moment so it'll stay open.
Other than that you could prepare a simple sample project/zip with folders and two animated tiles for example.

So later on I or someone else could try it and test it while adding the needed features in the export plugin.

**Comment by 5H4D0WILA** [comment]
oh, sorry
i didnt see the comment
i will create a sample zip

**Comment by mcarpenter622** [comment]
So with my last PR the folders issue should be resolved. I do not know the status of animated tiles as I haven't started working with those yet. Anyone else know if they're working now (This is a pretty old issue).

**Comment by bjorn** [comment]
@mcarpenter622 It's great that folders are working now! Animated tiles are definitely not supported yet. It's not very nice to have one issue for two different features, but I guess we could just leave this one open for now.

Regarding the animated tiles, I guess the question is whether Godot supports those, and if so, in which format it stores them.

**Comment by mcarpenter622** [comment]
I am considering closing this issue and opening one specifically for
animated tiles. I agree it's not great to have multiple feature requests in
a single issue number. Any concerns?

**Comment by mcarpenter622** [comment]
Closing this Issue since the folders are now working.
I have opened https://github.com/mapeditor/tiled-to-godot-export/issues/39 to track the export of animated tiles to Godot.
