### ISSUE TITLE
File paths on .tres export

### ISSUE THREAD

**Issue by Meway** [mapeditor/tiled-to-godot-export#15]
I run godot on a external drive. D://Godot/Project file/tileName.png
I have to manually change the .tres file to not use D://HDD Desktop/godot/making tiles/"tileName.png

My personal notes:
1. Click Map and file Export as .tscn file in folder
2. Click tileset and file Export as .tres in folder
3. Manually edit .tres folder to remove full path ie: "D://HDD Desktop/godot/making tiles/" (in this use case leave "assets" and beyond alone but leave "res://"
4. Open .tcsn file in Godot under FileSystem (fix .tres location) 
5. click (empty) under "Inspector next to "tile set" and select the .tres file.
6. repeat step 5. on each layer.

**Comment by mcarpenter622** [comment]
This should be fixed now. Please open a new issue if you have any additional issues.
