### ISSUE TITLE
Start using JavaScript modules

### ISSUE THREAD

**Issue by bjorn** [mapeditor/tiled-to-godot-export#36]
Since Tiled 1.8, there is support for [JavaScript modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules). Tiled will load JS files as modules when they have a `.mjs` extension. This enables the use of `import` and `export`.

Since this extension uses some shared code (utils.js), using JS modules would be the perfect way to encapsulate this shared code such that these helper functions don't pollute the global scope.

**Comment by eleniums** [comment]
Closed by PR #48
